steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--platform', 'linux/amd64',
    '-t', 'gcr.io/cora-450603/langchain-chatbot',
    '.'
  ]

# Push the container image to Container Registry
images: ['gcr.io/cora-450603/langchain-chatbot']

options:
  machineType: 'E2_HIGHCPU_8'  # Use a machine with more CPU for faster builds
  logging: CLOUD_LOGGING_ONLY